### ISSUE TITLE
"Stairs to Infinity" chaos ability

### ISSUE THREAD

**Issue by Hector-Xavier** [thepeopleseason/planechase#3]
The chaos ability of "Stairs to Infinity" allows you to "scry 1" your planar deck. At the app's present iteration, if you choose to keep the card on top of the deck and then planeswalk, then that card does not appear as it should.

To be specific: that would be expected during hellriding, because the deck is reshuffled before drawing cards for the new portion of the map. But during normal planeswalking and if no planes were removed from the edges of the map, the first drawn card should be the one you chose to keep on top of the deck. It seems that the planar deck is automatically shuffled before placing new Planes after planeswalking, even if no planes were removed from the edges of the map.

**Comment by thepeopleseason** [comment]
Thank you for the bug details. I'll respond when it's fixed.

**Comment by thepeopleseason** [comment]
This should be fixed now.
